eureka:
  instance:
    instance-id: onlyEurekaServer
    ip-address: 222.200.184.74
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
<<<<<<< HEAD
      defaultZone: http://222.200.184.74:8888/eureka/
  server:
    renewalPercentThreshold: 0.8
=======
      defaultZone: http://222.200.184.74:8888/eureka/
>>>>>>> c9ce903df66fa151612f875b4c001909a8b9b270
